In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
df_train = pd.read_csv('coursera_sessions_train.txt', sep=';', header=None, names=['watched', 'bought'])
df_train.head()

                               watched bought
0                          0,1,2,3,4,5    NaN
1                 9,10,11,9,11,12,9,11    NaN
2                    16,17,18,19,20,21    NaN
3                       24,25,26,27,24    NaN
4  34,35,36,34,37,35,36,37,38,39,38,39    NaN

In [27]:
df_test = pd.read_csv('coursera_sessions_test.txt', sep=';', header=None, names=['watched', 'bought'])
df_test.head()

             watched bought
0              6,7,8    NaN
1           13,14,15    NaN
2              22,23    NaN
3  28,29,30,31,32,33    NaN
4              40,41    NaN

In [30]:
from collections import Counter

watched_flat = [int(num) for elem in df_train['watched'] for num in elem.split(',')]
watched_freq = Counter(watched_flat)
watched_freq

Counter({0: 6,
         1: 6,
         2: 9,
         3: 7,
         4: 11,
         5: 4,
         9: 7,
         10: 7,
         11: 5,
         12: 17,
         16: 36,
         17: 70,
         18: 11,
         19: 35,
         20: 48,
         21: 11,
         24: 7,
         25: 6,
         26: 7,
         27: 15,
         34: 11,
         35: 22,
         36: 11,
         37: 8,
         38: 8,
         39: 4,
         42: 24,
         47: 2,
         48: 3,
         49: 1,
         59: 1,
         60: 2,
         61: 2,
         62: 1,
         63: 6,
         64: 3,
         65: 2,
         66: 2,
         67: 2,
         68: 2,
         71: 141,
         72: 167,
         73: 677,
         74: 36,
         76: 4,
         77: 49,
         78: 4,
         84: 12,
         85: 165,
         86: 10,
         87: 4,
         88: 1,
         89: 19,
         90: 13,
         91: 2,
         92: 12,
         93: 94,
         114: 129,
         115: 154,
         116: 22,
         117: 9,
         118: 27,
         119: 8,
         120: 3,
         121: 4,
         122: 24,
         123: 22,
         124: 41,
         129: 15,
         130: 13,
         131: 5,
         132: 12,
         133: 3,
         134: 6,
         137: 306,
         138: 33,
         139: 20,
         140: 73,
         141: 18,
         142: 36,
         143: 10,
         144: 43,
         97: 12,
         155: 22,
         156: 1,
         157: 43,
         163: 12,
         164: 1,
         165: 3,
         166: 90,
         173: 12,
         174: 17,
         175: 11,
         176: 55,
         136: 84,
         192: 84,
         195: 60,
         196: 55,
         198: 24,
         199: 21,
         127: 101,
         206: 14,
         207: 37,
         216: 1,
         217: 1,
         220: 5,
         223: 42,
         224: 22,
         225: 11,
         241: 85,
         242: 22,
         243: 50,
         244: 9,
         245: 10,
         246: 17,
         247: 14,
         248: 11,
         249: 23,
         253: 3,
         254: 2,
         169: 4,
         262: 387,
         263: 56,
         264: 84,
         265: 1,
         266: 2,
         267: 4,
         268: 3,
         269: 6,
         270: 4,
         271: 1,
         272: 1,
         273: 11,
         274: 1,
         275: 1,
         276: 2,
         277: 1,
         278: 3,
         279: 5,
         280: 4,
         281: 9,
         282: 3,
         283: 6,
         291: 22,
         296: 6,
         297: 7,
         298: 2,
         299: 2,
         303: 16,
         304: 2,
         305: 1,
         306: 3,
         307: 2,
         308: 1,
         309: 2,
         310: 2,
         311: 1,
         312: 1,
         332: 9,
         333: 3,
         334: 1,
         8: 225,
         339: 62,
         340: 22,
         341: 100,
         342: 36,
         343: 164,
         344: 26,
         352: 50,
         353: 3,
         361: 103,
         362: 61,
         363: 147,
         364: 25,
         365: 37,
         178: 19,
         179: 21,
         366: 14,
         367: 12,
         368: 14,
         369: 26,
         370: 9,
         161: 74,
         374: 60,
         375: 82,
         379: 2,
         384: 48,
         385: 3,
         386: 1,
         390: 61,
         391: 57,
         392: 19,
         406: 35,
         407: 8,
         408: 27,
         409: 11,
         413: 2,
         414: 27,
         415: 11,
         416: 18,
         417: 1,
         418: 13,
         419: 4,
         420: 4,
         421: 2,
         423: 5,
         424: 3,
         425: 2,
         426: 10,
         433: 5,
         434: 2,
         435: 2,
         439: 27,
         440: 12,
         446: 11,
         447: 2,
         448: 3,
         449: 3,
         450: 1,
         451: 1,
         452: 4,
         453: 2,
         454: 5,
         455: 6,
         456: 5,
         458: 29,
         459: 4,
         460: 8,
         463: 8,
         464: 52,
         475: 2,
         476: 1,
         477: 4,
         478: 3,
         479: 3,
         481: 1,
         486: 14,
         487: 11,
         488: 8,
         489: 16,
         490: 9,
         491: 6,
         492: 6,
         493: 6,
         494: 12,
         496: 4,
         497: 13,
         240: 22,
         498: 6,
         504: 8,
         505: 4,
         506: 6,
         507: 3,
         510: 79,
         511: 62,
         512: 37,
         513: 56,
         514: 18,
         515: 5,
         519: 44,
         522: 15,
         523: 56,
         531: 5,
         532: 1,
         533: 2,
         534: 1,
         535: 1,
         536: 5,
         537: 1,
         538: 2,
         539: 1,
         540: 1,
         541: 1,
         542: 1,
         547: 76,
         548: 13,
         549: 12,
         550: 15,
         551: 177,
         552: 125,
         162: 318,
         553: 135,
         558: 3,
         556: 30,
         559: 3,
         560: 12,
         561: 15,
         562: 23,
         563: 15,
         564: 11,
         565: 25,
         566: 6,
         567: 3,
         568: 16,
         569: 13,
         570: 11,
         571: 1,
         572: 1,
         573: 3,
         574: 5,
         575: 3,
         576: 2,
         589: 5,
         582: 7,
         590: 7,
         581: 10,
         585: 1,
         583: 1,
         577: 3,
         591: 115,
         592: 5,
         579: 3,
         593: 10,
         599: 43,
         600: 9,
         601: 56,
         602: 31,
         204: 396,
         609: 213,
         28: 148,
         610: 96,
         611: 65,
         33: 60,
         612: 40,
         613: 13,
         614: 17,
         615: 50,
         616: 9,
         617: 14,
         618: 6,
         619: 5,
         620: 14,
         623: 5,
         624: 19,
         625: 19,
         626: 8,
         627: 3,
         187: 36,
         635: 25,
         636: 15,
         637: 4,
         638: 7,
         642: 38,
         643: 39,
         644: 36,
         645: 31,
         650: 50,
         651: 6,
         652: 2,
         655: 18,
         656: 7,
         657: 12,
         658: 6,
         659: 23,
         668: 1,
         669: 1,
         670: 1,
         671: 24,
         672: 20,
         673: 18,
         674: 8,
         675: 1,
         687: 7,
         688: 4,
         689: 1,
         690: 3,
         691: 4,
         692: 1,
         699: 2,
         700: 1,
         704: 8,
         705: 4,
         706: 6,
         259: 173,
         709: 16,
         710: 26,
         711: 57,
         712: 54,
         713: 43,
         714: 20,
         715: 8,
         716: 1,
         717: 2,
         718: 13,
         727: 1,
         728: 3,
         729: 2,
         730: 3,
         742: 30,
         743: 62,
         744: 34,
         745: 16,
         750: 38,
         751: 197,
         752: 16,
         791: 140,
         320: 34,
         785: 27,
         792: 8,
         793: 16,
         794: 17,
         795: 27,
         796: 63,
         797: 9,
         746: 118,
         753: 6,
         798: 6,
         754: 7,
         799: 45,
         800: 253,
         801: 26,
         810: 14,
         811: 3,
         812: 3,
         817: 1,
         818: 1,
         819: 1,
         820: 1,
         821: 1,
         824: 7,
         825: 32,
         828: 88,
         829: 35,
         830: 36,
         833: 48,
         834: 26,
         837: 19,
         838: 4,
         839: 3,
         840: 4,
         842: 24,
         845: 2,
         846: 3,
         847: 66,
         850: 3,
         851: 1,
         852: 5,
         854: 6,
         855: 45,
         874: 12,
         875: 139,
         876: 9,
         877: 55,
         878: 27,
         879: 153,
         884: 138,
         170: 280,
         885: 14,
         886: 18,
         887: 26,
         894: 2,
         895: 4,
         896: 4,
         897: 2,
         898: 9,
         899: 13,
         900: 7,
         901: 15,
         902: 1,
         903: 12,
         918: 110,
         919: 47,
         920: 66,
         922: 4,
         923: 4,
         924: 8,
         925: 49,
         926: 1,
         927: 4,
         238: 10,
         928: 7,
         929: 8,
         239: 15,
         930: 13,
         931: 2,
         933: 7,
         934: 2,
         935: 2,
         936: 1,
         940: 1,
         942: 8,
         943: 8,
         944: 3,
         947: 2,
         948: 5,
         135: 44,
         956: 11,
         958: 16,
         959: 7,
         960: 48,
         964: 3,
         965: 1,
         967: 53,
         968: 8,
         969: 18,
         970: 96,
         975: 14,
         976: 2,
         985: 2,
         986: 2,
         987: 3,
         988: 1,
         1008: 93,
         1009: 78,
         1010: 27,
         1011: 122,
         1014: 10,
         1015: 11,
         1016: 7,
         1028: 24,
         1029: 12,
         1033: 3,
         1034: 2,
         1036: 1,
         1037: 7,
         1038: 2,
         1041: 19,
         1042: 65,
         1043: 55,
         1047: 4,
         1048: 1,
         1049: 2,
         1052: 9,
         1053: 1,
         1059: 11,
         1060: 1,
         1061: 2,
         1062: 1,
         1064: 75,
         1065: 3,
         1066: 57,
         1067: 10,
         1068: 4,
         1069: 20,
         1070: 2,
         1071: 9,
         1072: 11,
         1073: 1,
         1074: 6,
         1075: 9,
         1076: 2,
         1077: 21,
         1078: 7,
         1079: 46,
         1080: 2,
         1081: 21,
         1082: 12,
         1085: 108,
         6: 283,
         302: 144,
         318: 29,
         1093: 7,
         1094: 20,
         805: 83,
         1095: 9,
         1096: 11,
         1097: 40,
         1098: 4,
         1101: 6,
         1102: 6,
         1106: 6,
         1107: 12,
         1108: 2,
         1109: 9,
         966: 122,
         250: 17,
         1113: 10,
         1117: 4,
         1118: 27,
         1127: 35,
         1128: 34,
         1129: 10,
         1130: 31,
         1131: 17,
         1132: 14,
         1133: 8,
         1134: 5,
         1137: 42,
         1138: 19,
         1139: 51,
         1140: 118,
         1141: 82,
         1142: 62,
         1143: 12,
         1144: 40,
         1145: 22,
         1146: 18,
         1147: 17,
         1148: 8,
         1149: 25,
         1150: 42,
         1151: 52,
         1156: 1,
         1157: 27,
         1158: 5,
         1159: 8,
         1169: 5,
         1163: 2,
         1170: 5,
         1164: 7,
         1171: 2,
         1168: 1,
         1172: 3,
         1173: 4,
         1178: 18,
         1179: 22,
         1180: 7,
         1181: 95,
         1182: 14,
         1183: 10,
         1187: 2,
         1188: 37,
         1189: 7,
         1190: 17,
         1191: 12,
         1194: 2,
         1195: 5,
         1198: 56,
         1199: 1,
         1200: 14,
         1201: 11,
         1202: 14,
         1208: 7,
         1209: 9,
         13: 10,
         1210: 33,
         1211: 1,
         1215: 16,
         1216: 4,
         1217: 6,
         1218: 7,
         1219: 6,
         1227: 6,
         1228: 6,
         1229: 2,
         1230: 5,
         1231: 10,
         1232: 2,
         1256: 44,
         1266: 1,
         1267: 1,
         1268: 2,
         1274: 5,
         1275: 5,
         1277: 116,
         158: 641,
         1284: 4,
         1290: 4,
         1291: 7,
         1292: 20,
         1293: 17,
         1297: 12,
         1298: 5,
         1299: 5,
         1300: 15,
         1304: 2,
         1305: 2,
         1306: 15,
         469: 124,
         1308: 37,
         1312: 51,
         1313: 40,
         1314: 50,
         1315: 44,
         1316: 31,
         1317: 46,
         1318: 19,
         1319: 39,
         1320: 16,
         1321: 47,
         1323: 159,
         1324: 54,
         1325: 5,
         1328: 11,
         1329: 4,
         1330: 5,
         1331: 11,
         1332: 10,
         1333: 1,
         1338: 38,
         1339: 69,
         1340: 8,
         1341: 27,
         1184: 186,
         1345: 67,
         126: 100,
         1346: 199,
         1347: 52,
         1212: 47,
         749: 15,
         1349: 140,
         1350: 18,
         1351: 18,
         1352: 36,
         1353: 19,
         1354: 15,
         1355: 23,
         1360: 17,
         1367: 7,
         1368: 6,
         1373: 1,
         1374: 9,
         1375: 3,
         1376: 1,
         1377: 1,
         1382: 57,
         1383: 1,
         1384: 2,
         1385: 2,
         1386: 2,
         1387: 9,
         1388: 2,
         1389: 1,
         1393: 2,
         1396: 7,
         1397: 2,
         1398: 10,
         1399: 4,
         1407: 3,
         1408: 4,
         1410: 2,
         1414: 35,
         977: 64,
         1417: 6,
         1423: 3,
         1424: 3,
         1425: 1,
         1426: 16,
         1427: 19,
         1431: 36,
         1432: 31,
         1433: 41,
         1436: 1,
         1437: 1,
         1214: 149,
         1444: 1,
         1445: 2,
         1446: 1,
         1447: 1,
         1451: 4,
         1452: 3,
         1453: 3,
         1454: 3,
         1460: 2,
         1461: 1,
         1462: 2,
         1463: 12,
         1466: 3,
         1467: 23,
         1468: 10,
         1469: 23,
         1470: 27,
         1471: 1,
         1472: 1,
         1473: 3,
         1477: 21,
         756: 24,
         1478: 8,
         1475: 69,
         1474: 91,
         1479: 11,
         1480: 17,
         202: 66,
         1483: 57,
         200: 18,
         1484: 7,
         1485: 2,
         1486: 16,
         1491: 17,
         1492: 18,
         1494: 98,
         1495: 31,
         1496: 53,
         1497: 28,
         1498: 47,
         1499: 39,
         1500: 12,
         1501: 8,
         1502: 35,
         1503: 24,
         1504: 6,
         1505: 16,
         1506: 22,
         1507: 25,
         1508: 14,
         1509: 14,
         1510: 15,
         1511: 10,
         1512: 7,
         1513: 12,
         1514: 12,
         1515: 5,
         1516: 4,
         106: 82,
         1517: 35,
         1523: 39,
         1524: 27,
         1525: 1,
         1535: 32,
         1536: 58,
         1540: 36,
         1541: 1,
         1545: 8,
         317: 63,
         1548: 30,
         1549: 71,
         1550: 12,
         779: 66,
         1551: 81,
         1552: 60,
         1553: 8,
         1554: 6,
         1555: 2,
         1556: 1,
         858: 2,
         1560: 4,
         1561: 14,
         1562: 2,
         1564: 6,
         1565: 5,
         1566: 8,
         1568: 5,
         1571: 43,
         1572: 33,
         1573: 9,
         1570: 4,
         1574: 5,
         1575: 4,
         1576: 2,
         1577: 4,
         1578: 1,
         1579: 1,
         1580: 2,
         1581: 2,
         1582: 1,
         1583: 3,
         1584: 9,
         1585: 4,
         1586: 12,
         1587: 4,
         1592: 38,
         1593: 2,
         1594: 2,
         1616: 3,
         1617: 1,
         1618: 2,
         1619: 2,
         1620: 3,
         1621: 4,
         1622: 3,
         1623: 25,
         1626: 3,
         1627: 6,
         1628: 7,
         1629: 1,
         1630: 6,
         1631: 4,
         1632: 2,
         1633: 2,
         1634: 50,
         1635: 16,
         1636: 4,
         1640: 5,
         1641: 4,
         1642: 6,
         1646: 3,
         1647: 4,
         1648: 48,
         1649: 61,
         1650: 50,
         1651: 131,
         1652: 23,
         1653: 32,
         1654: 87,
         1657: 39,
         1658: 18,
         1659: 2,
         1660: 72,
         1661: 3,
         1662: 12,
         1666: 11,
         1669: 44,
         1670: 25,
         1671: 24,
         1672: 26,
         1693: 4,
         1694: 2,
         1695: 1,
         1696: 1,
         1697: 1,
         1698: 11,
         1699: 3,
         1700: 3,
         1701: 9,
         1702: 7,
         1703: 1,
         1704: 7,
         1710: 20,
         1711: 34,
         1712: 8,
         1713: 22,
         1722: 7,
         1723: 7,
         1724: 3,
         1727: 7,
         1729: 9,
         1730: 10,
         1734: 2,
         1735: 4,
         1736: 7,
         1737: 5,
         1741: 7,
         1742: 2,
         1743: 2,
         1744: 1,
         1748: 21,
         1749: 15,
         1750: 63,
         1751: 9,
         1415: 16,
         1752: 6,
         1753: 29,
         1754: 3,
         1758: 2,
         1759: 5,
         1760: 15,
         1761: 21,
         1762: 5,
         1763: 9,
         1764: 2,
         1765: 6,
         1766: 6,
         1767: 11,
         1768: 8,
         1769: 14,
         1773: 17,
         1774: 21,
         1775: 20,
         1776: 10,
         1777: 1,
         1778: 23,
         1779: 14,
         1786: 3,
         1787: 3,
         1789: 22,
         1790: 13,
         1791: 9,
         1792: 1,
         1795: 54,
         1796: 9,
         1802: 6,
         1803: 4,
         1804: 5,
         1807: 43,
         1808: 23,
         1809: 21,
         1806: 16,
         1810: 12,
         1811: 1,
         1812: 2,
         1818: 103,
         1819: 24,
         1820: 12,
         1821: 59,
         1822: 25,
         1823: 11,
         1824: 7,
         335: 78,
         1831: 15,
         1832: 26,
         1833: 2,
         1842: 17,
         1846: 2,
         1847: 62,
         1848: 18,
         99: 73,
         1861: 12,
         1862: 14,
         1863: 2,
         1864: 7,
         1865: 10,
         1872: 2,
         1873: 2,
         1874: 1,
         1875: 2,
         1876: 2,
         1878: 14,
         1879: 3,
         1880: 8,
         1881: 3,
         1890: 1,
         1891: 8,
         1892: 5,
         1893: 11,
         1894: 6,
         1895: 1,
         1896: 1,
         1897: 7,
         1898: 2,
         1899: 6,
         ...})

In [31]:
df_train = df_train[df_train['bought'].notnull()]
df_train.shape

(3608, 2)

In [157]:
df_test = df_test[df_test['bought'].notnull()]
df_test.shape

(3665, 2)

In [32]:
bought_flat = [int(num) for elem in df_train['bought'] for num in elem.split(',')]
bought_freq = Counter(bought_flat)
bought_freq

Counter({67: 1,
         60: 1,
         63: 1,
         86: 2,
         199: 1,
         303: 1,
         352: 2,
         519: 4,
         603: 1,
         604: 1,
         602: 2,
         599: 1,
         605: 6,
         606: 2,
         600: 1,
         690: 1,
         688: 1,
         851: 1,
         879: 1,
         1118: 3,
         1545: 1,
         1727: 1,
         99: 1,
         1907: 1,
         1959: 1,
         1998: 2,
         2013: 2,
         2019: 1,
         2462: 1,
         2520: 1,
         2543: 1,
         1526: 1,
         2764: 1,
         2857: 1,
         2853: 1,
         2852: 1,
         2920: 1,
         2930: 2,
         3033: 2,
         3026: 2,
         3032: 1,
         3031: 1,
         3102: 1,
         3100: 1,
         1260: 1,
         3204: 1,
         3207: 1,
         3217: 1,
         3267: 1,
         3443: 3,
         3529: 1,
         3584: 1,
         3564: 1,
         3612: 3,
         3623: 1,
         3645: 1,
         3561: 1,
         1662: 1,
         3741: 1,
         3979: 1,
         4216: 1,
         4246: 1,
         4298: 1,
         3066: 1,
         4512: 2,
         4750: 2,
         4815: 4,
         5058: 1,
         5066: 1,
         5134: 1,
         5135: 1,
         5183: 2,
         970: 1,
         5209: 1,
         805: 2,
         29: 1,
         6000: 1,
         6090: 1,
         6142: 1,
         412: 1,
         1011: 2,
         6456: 1,
         6585: 1,
         6597: 1,
         6603: 1,
         6606: 2,
         6622: 1,
         6699: 1,
         6764: 1,
         6926: 1,
         3288: 1,
         7224: 1,
         7236: 1,
         7278: 1,
         4477: 1,
         7968: 1,
         6367: 1,
         7989: 2,
         7979: 2,
         7986: 3,
         7978: 1,
         1714: 3,
         8028: 1,
         8062: 1,
         8060: 1,
         4670: 2,
         8139: 1,
         8370: 1,
         8521: 1,
         8538: 1,
         8548: 1,
         8547: 2,
         8546: 1,
         8603: 2,
         8630: 1,
         8136: 5,
         8770: 1,
         9074: 1,
         9073: 1,
         9075: 1,
         9476: 1,
         3547: 1,
         4240: 2,
         9518: 1,
         9562: 1,
         9558: 1,
         9581: 1,
         9623: 4,
         9643: 3,
         5914: 1,
         4089: 5,
         9644: 1,
         9694: 1,
         9845: 1,
         10016: 1,
         10064: 1,
         4938: 2,
         10083: 1,
         10277: 1,
         10327: 1,
         10386: 1,
         5438: 1,
         9519: 1,
         10640: 1,
         10786: 1,
         10787: 1,
         10797: 1,
         4593: 1,
         11238: 1,
         11262: 1,
         11284: 1,
         11310: 1,
         11424: 1,
         11426: 1,
         2337: 2,
         1111: 1,
         1342: 2,
         11918: 1,
         12202: 1,
         1603: 1,
         12296: 1,
         12351: 1,
         4687: 1,
         6772: 1,
         12648: 1,
         10909: 1,
         13040: 1,
         12882: 2,
         13185: 2,
         13188: 1,
         3323: 1,
         5774: 1,
         9021: 1,
         5810: 1,
         13263: 1,
         13397: 1,
         13471: 1,
         13550: 2,
         13541: 3,
         13576: 1,
         13760: 1,
         12647: 1,
         13865: 1,
         13861: 1,
         7983: 3,
         2531: 1,
         13877: 1,
         13902: 1,
         13906: 1,
         13925: 2,
         13946: 1,
         14062: 3,
         10802: 1,
         3739: 1,
         14072: 1,
         3735: 1,
         14098: 1,
         3738: 1,
         7908: 3,
         3083: 1,
         14246: 1,
         14316: 1,
         14349: 3,
         12485: 1,
         14517: 1,
         14710: 1,
         14711: 1,
         13777: 1,
         14835: 2,
         2705: 1,
         9834: 2,
         14852: 2,
         14861: 1,
         14902: 1,
         14901: 1,
         15206: 1,
         14704: 1,
         15409: 1,
         15419: 1,
         15452: 1,
         13673: 2,
         15570: 1,
         15746: 1,
         3445: 6,
         15805: 2,
         5569: 10,
         3324: 11,
         4894: 2,
         16093: 1,
         16083: 1,
         16080: 1,
         1736: 2,
         16089: 1,
         16086: 1,
         16140: 1,
         262: 4,
         6078: 1,
         16196: 1,
         16209: 1,
         11899: 4,
         15480: 1,
         16359: 2,
         2929: 5,
         10244: 3,
         16521: 1,
         7884: 1,
         3149: 10,
         16709: 1,
         16823: 1,
         7863: 1,
         16825: 1,
         16828: 2,
         2446: 1,
         17026: 1,
         16279: 1,
         8372: 1,
         2740: 1,
         17280: 1,
         17418: 1,
         17455: 1,
         17583: 2,
         13157: 1,
         17915: 1,
         18129: 1,
         18162: 1,
         18164: 1,
         15353: 1,
         3964: 1,
         18180: 1,
         12187: 1,
         7306: 1,
         18551: 1,
         18556: 1,
         14768: 2,
         18677: 1,
         1962: 1,
         7465: 1,
         18708: 1,
         18700: 1,
         18697: 1,
         2257: 1,
         6730: 1,
         15907: 1,
         2070: 4,
         18869: 1,
         18887: 1,
         18963: 1,
         18985: 1,
         2513: 1,
         6179: 2,
         4599: 3,
         5570: 6,
         1242: 1,
         6080: 1,
         14574: 2,
         11225: 3,
         474: 1,
         19268: 1,
         19316: 1,
         1729: 2,
         19335: 1,
         10348: 1,
         19333: 2,
         19334: 1,
         18735: 1,
         6659: 1,
         8145: 2,
         19926: 1,
         2057: 2,
         20003: 3,
         20025: 2,
         803: 1,
         4539: 1,
         8723: 1,
         10844: 1,
         10241: 1,
         16479: 2,
         20235: 1,
         20294: 1,
         9050: 1,
         20318: 1,
         3353: 2,
         20535: 1,
         21842: 1,
         7631: 5,
         18201: 1,
         13665: 1,
         1949: 3,
         9408: 1,
         22024: 1,
         2845: 1,
         17261: 1,
         2580: 2,
         22240: 1,
         22244: 1,
         22243: 1,
         17719: 1,
         10239: 2,
         22472: 1,
         11136: 1,
         4093: 1,
         22494: 1,
         10875: 2,
         1140: 2,
         22553: 2,
         22550: 1,
         17944: 1,
         5894: 4,
         2339: 1,
         881: 1,
         11764: 1,
         22797: 1,
         1815: 1,
         22940: 1,
         7611: 1,
         23068: 1,
         422: 5,
         23265: 1,
         22791: 1,
         4393: 1,
         23341: 2,
         17654: 1,
         1852: 7,
         23398: 1,
         23400: 1,
         23415: 1,
         13284: 1,
         1309: 1,
         23539: 1,
         18141: 1,
         23624: 1,
         23642: 2,
         23625: 2,
         16067: 2,
         4441: 1,
         5913: 1,
         4053: 1,
         23847: 1,
         158: 14,
         20056: 1,
         23903: 1,
         23970: 1,
         23972: 1,
         24008: 1,
         24055: 1,
         16884: 1,
         24049: 1,
         24047: 1,
         16883: 1,
         24052: 1,
         24161: 1,
         24220: 1,
         24223: 2,
         24219: 1,
         16371: 1,
         24442: 1,
         24500: 1,
         18729: 1,
         17481: 1,
         4394: 3,
         5995: 1,
         24771: 1,
         24772: 1,
         4715: 2,
         10804: 2,
         24801: 1,
         24806: 1,
         918: 2,
         12811: 1,
         4029: 1,
         25021: 1,
         25076: 1,
         25145: 1,
         25152: 1,
         25272: 1,
         21177: 1,
         20416: 1,
         25384: 2,
         6323: 2,
         16988: 1,
         2296: 1,
         25602: 1,
         25601: 1,
         25604: 1,
         25615: 1,
         2065: 1,
         17499: 1,
         10464: 1,
         25867: 1,
         16014: 1,
         734: 2,
         4643: 2,
         16793: 1,
         26100: 1,
         26101: 1,
         26121: 1,
         26132: 1,
         7726: 1,
         11434: 2,
         26141: 1,
         22373: 1,
         26195: 1,
         26234: 1,
         8764: 2,
         21324: 1,
         20653: 1,
         8149: 1,
         21738: 2,
         547: 1,
         2193: 3,
         1544: 1,
         1058: 5,
         3889: 2,
         3410: 4,
         26727: 1,
         11037: 2,
         26819: 1,
         3785: 2,
         5780: 3,
         25942: 1,
         126: 1,
         5734: 1,
         16074: 1,
         5202: 4,
         2106: 1,
         27106: 1,
         27110: 2,
         27128: 1,
         27124: 1,
         27133: 1,
         21141: 1,
         9602: 2,
         22881: 1,
         4292: 1,
         21803: 1,
         27791: 1,
         27792: 1,
         27786: 1,
         300: 2,
         11120: 1,
         10574: 1,
         27955: 1,
         21704: 1,
         2747: 2,
         4110: 1,
         28219: 1,
         28277: 1,
         11663: 1,
         23087: 1,
         8371: 2,
         28499: 1,
         5985: 1,
         25205: 1,
         11693: 2,
         28571: 1,
         28763: 1,
         14091: 1,
         28931: 1,
         28923: 2,
         1651: 3,
         28934: 1,
         215: 1,
         5501: 5,
         29046: 1,
         23471: 1,
         29644: 1,
         20168: 1,
         29642: 1,
         2861: 5,
         29673: 1,
         4408: 1,
         29694: 2,
         29670: 1,
         29795: 1,
         3509: 2,
         29872: 1,
         30072: 1,
         25197: 1,
         6: 2,
         30149: 1,
         30228: 1,
         30227: 1,
         21714: 1,
         11462: 3,
         20119: 1,
         3853: 1,
         16742: 1,
         30307: 1,
         30357: 3,
         30376: 1,
         5962: 1,
         28876: 1,
         30448: 1,
         30421: 1,
         30526: 1,
         18737: 1,
         7552: 2,
         30725: 1,
         1315: 3,
         1316: 1,
         12718: 1,
         1871: 2,
         30866: 1,
         30882: 1,
         30883: 1,
         30865: 1,
         30884: 1,
         30885: 1,
         11746: 1,
         14223: 1,
         29871: 1,
         30981: 1,
         30723: 1,
         31093: 1,
         31092: 1,
         4396: 1,
         4399: 1,
         31140: 1,
         31246: 1,
         17498: 1,
         9007: 1,
         31350: 1,
         31351: 1,
         8338: 4,
         31352: 1,
         14854: 2,
         18749: 2,
         8340: 2,
         14853: 1,
         31239: 1,
         31373: 1,
         31483: 1,
         31478: 1,
         73: 11,
         7461: 1,
         545: 1,
         10868: 1,
         14565: 2,
         32221: 1,
         32225: 2,
         44: 1,
         32266: 1,
         32339: 1,
         32354: 1,
         138: 1,
         13427: 1,
         3784: 3,
         18071: 1,
         10619: 2,
         38: 1,
         31573: 1,
         32855: 1,
         33036: 1,
         16226: 1,
         21175: 1,
         33099: 1,
         33100: 1,
         33101: 1,
         19007: 1,
         17391: 1,
         20783: 4,
         4194: 1,
         4208: 1,
         33180: 1,
         33176: 1,
         808: 1,
         32263: 3,
         2873: 1,
         2245: 1,
         19640: 3,
         33459: 1,
         31946: 1,
         33534: 1,
         20230: 1,
         23006: 2,
         33745: 1,
         33793: 1,
         7613: 1,
         33909: 1,
         33911: 1,
         34010: 1,
         20600: 1,
         1728: 3,
         1934: 1,
         14456: 1,
         2728: 1,
         34452: 1,
         3855: 2,
         34492: 1,
         25111: 1,
         34607: 1,
         34622: 1,
         5907: 1,
         25941: 1,
         2729: 2,
         29573: 1,
         2316: 1,
         3602: 1,
         20456: 1,
         872: 3,
         22317: 1,
         15328: 2,
         35122: 1,
         11119: 1,
         27244: 1,
         25119: 1,
         14497: 1,
         35255: 1,
         28802: 2,
         5646: 1,
         20510: 2,
         35371: 1,
         35446: 2,
         2871: 1,
         6805: 3,
         35552: 1,
         1843: 5,
         26517: 1,
         4646: 1,
         33668: 1,
         10886: 5,
         26922: 2,
         26920: 1,
         5105: 1,
         1654: 2,
         35807: 1,
         35806: 1,
         6037: 1,
         35826: 1,
         2241: 2,
         9801: 1,
         35931: 1,
         32086: 1,
         5558: 1,
         18781: 1,
         2654: 2,
         7195: 1,
         5146: 2,
         34388: 1,
         5970: 1,
         22672: 1,
         16478: 1,
         36282: 1,
         28705: 2,
         20073: 1,
         33250: 1,
         36461: 1,
         36509: 1,
         36618: 1,
         1845: 2,
         1370: 2,
         7491: 2,
         22590: 1,
         743: 4,
         11276: 1,
         14383: 1,
         17477: 1,
         36945: 1,
         513: 1,
         2842: 2,
         37155: 1,
         1522: 1,
         1637: 1,
         14748: 1,
         4845: 2,
         8596: 1,
         3870: 2,
         2044: 3,
         37491: 1,
         37494: 1,
         6243: 1,
         10040: 2,
         37670: 1,
         2049: 1,
         27961: 1,
         37762: 1,
         37764: 1,
         37763: 1,
         14130: 1,
         5034: 1,
         7931: 3,
         37798: 1,
         37836: 1,
         15431: 2,
         1625: 1,
         29800: 1,
         37954: 1,
         17001: 1,
         37981: 1,
         1656: 2,
         38157: 1,
         1534: 2,
         14909: 1,
         1346: 2,
         38244: 1,
         24115: 2,
         16194: 4,
         38409: 1,
         9552: 2,
         5318: 1,
         6052: 1,
         9005: 1,
         13178: 1,
         10034: 2,
         38607: 1,
         38614: 1,
         38611: 1,
         38609: 1,
         22462: 2,
         22460: 1,
         38789: 1,
         38823: 1,
         85: 1,
         38846: 2,
         25735: 1,
         34120: 1,
         750: 2,
         30594: 1,
         38896: 1,
         10237: 2,
         23987: 1,
         38972: 1,
         22599: 2,
         4744: 1,
         1186: 1,
         21914: 1,
         4490: 2,
         39144: 1,
         39145: 1,
         39161: 1,
         3936: 1,
         5651: 2,
         30: 1,
         1750: 2,
         16526: 1,
         39505: 1,
         33404: 1,
         39567: 1,
         39568: 1,
         34717: 1,
         39570: 1,
         39574: 2,
         7790: 2,
         39575: 1,
         18898: 1,
         4034: 1,
         2340: 1,
         39654: 1,
         39653: 1,
         39658: 1,
         1314: 4,
         39669: 1,
         39762: 1,
         28606: 1,
         19308: 1,
         39907: 1,
         39969: 1,
         39982: 1,
         20304: 2,
         40054: 1,
         40055: 1,
         40067: 1,
         40091: 1,
         40085: 1,
         40086: 1,
         40092: 1,
         40089: 1,
         28895: 1,
         28222: 1,
         31529: 1,
         2738: 2,
         9717: 1,
         40254: 1,
         40250: 1,
         40252: 1,
         40411: 1,
         7109: 2,
         40410: 1,
         40409: 1,
         438: 2,
         4025: 1,
         14160: 1,
         40548: 1,
         32689: 2,
         93: 1,
         31135: 1,
         9132: 1,
         9466: 3,
         8530: 2,
         40715: 1,
         1054: 1,
         21772: 3,
         37944: 1,
         21485: 1,
         15226: 1,
         40910: 1,
         40915: 1,
         32275: 1,
         5144: 1,
         40906: 1,
         29480: 1,
         40911: 1,
         40909: 1,
         40913: 1,
         40916: 1,
         32678: 1,
         17000: 2,
         8422: 2,
         291: 1,
         41082: 1,
         41084: 1,
         17188: 2,
         41189: 1,
         22386: 3,
         41369: 1,
         1181: 9,
         5924: 2,
         41566: 1,
         41559: 1,
         41562: 1,
         3809: 2,
         41664: 1,
         41689: 1,
         15542: 1,
         41704: 1,
         41806: 2,
         8339: 1,
         35360: 1,
         38122: 1,
         4708: 1,
         745: 1,
         9107: 1,
         2720: 1,
         41846: 1,
         41612: 1,
         4906: 1,
         204: 12,
         12779: 2,
         41851: 1,
         4535: 2,
         19789: 1,
         42080: 1,
         42106: 1,
         31204: 1,
         42268: 1,
         6596: 2,
         4586: 2,
         10910: 1,
         18748: 1,
         13626: 1,
         42492: 1,
         16308: 1,
         7911: 2,
         17109: 1,
         751: 4,
         21325: 1,
         1678: 1,
         39430: 1,
         11024: 2,
         42663: 1,
         7522: 1,
         510: 1,
         4042: 1,
         391: 1,
         7132: 1,
         10944: 1,
         16976: 1,
         30006: 1,
         21690: 1,
         14204: 1,
         25324: 1,
         42950: 2,
         42994: 1,
         887: 2,
         21812: 1,
         43064: 2,
         43126: 1,
         43131: 1,
         43125: 1,
         43128: 1,
         43132: 1,
         43123: 1,
         24597: 1,
         38323: 1,
         15804: 1,
         13664: 1,
         43169: 1,
         359: 1,
         43199: 1,
         43224: 1,
         43274: 1,
         43281: 1,
         43298: 1,
         7379: 4,
         43296: 1,
         24063: 1,
         41990: 1,
         43414: 1,
         6565: 1,
         1979: 2,
         43479: 1,
         43530: 1,
         6133: 1,
         43556: 1,
         6020: 4,
         7686: 4,
         4335: 7,
         43870: 1,
         35506: 1,
         43935: 1,
         43958: 1,
         34250: 1,
         33567: 1,
         44165: 1,
         160: 4,
         3283: 1,
         44285: 1,
         2397: 2,
         13126: 1,
         23649: 1,
         44425: 1,
         15940: 1,
         18692: 1,
         1813: 1,
         5926: 1,
         44662: 1,
         11185: 3,
         19447: 1,
         13245: 1,
         44703: 1,
         3793: 5,
         758: 3,
         20698: 1,
         16121: 1,
         2913: 1,
         44899: 1,
         16252: 1,
         8614: 2,
         71: 4,
         4222: 1,
         13448: 1,
         45016: 1,
         39170: 1,
         11532: 2,
         11105: 1,
         21928: 1,
         27621: 2,
         5657: 1,
         32828: 2,
         13553: 1,
         10378: 1,
         26559: 1,
         7029: 2,
         45495: 1,
         45496: 1,
         30681: 2,
         1320: 2,
         15922: 2,
         35827: 2,
         45605: 1,
         ...})

In [143]:
watched_rate = sorted(watched_freq, key=watched_freq.get, reverse=True)
bought_rate = sorted(bought_freq, key=bought_freq.get, reverse=True)

In [171]:
def sort_list_by_watched(l):
    return sorted(set(l), key=lambda x: watched_freq.get(int(x), 0), reverse=True)

def sort_list_by_bought(l):
    return sorted(set(l), key=lambda x: bought_freq.get(int(x), 0), reverse=True)

def average_precision(k, df, mode):
    precisions = []
    for index, row in df.iterrows():
        if mode == 'watched':
            recomendations = set(sort_list_by_watched(row['watched'])[:k])
        elif mode == 'bought':
            recomendations = set(sort_list_by_bought(row['watched'])[:k])
        precision = len(recomendations.intersection(row['bought'])) / min(k, len(recomendations))
        precisions.append(precision)
    return round(sum(precisions) / len(precisions), 2)

def average_recall(k, df, mode):
    precisions = []
    for index, row in df.iterrows():
        if mode == 'watched':
            recomendations = set(sort_list_by_watched(row['watched'])[:k])
        elif mode == 'bought':
            recomendations = set(sort_list_by_bought(row['watched'])[:k])
        precision = len(recomendations.intersection(row['bought'])) / len(row['bought'])
        precisions.append(precision)
    return round(sum(precisions) / len(precisions), 2)

In [162]:
average_precision(5, df_train, 'watched')
print(sort_list_by_watched(df_train['watched'][7]))
print(df_train['bought'][7])

['63', '64', '61', '60', '67', '68', '66', '65', '62', '59']
['67', '60', '63']

In [172]:
with open('ans_1', 'w') as fout:
    fout.write(' '.join([str(average_recall(1, df_train, 'watched')),
                         str(average_precision(1, df_train, 'watched')),
                         str(average_recall(5, df_train, 'watched')),
                         str(average_precision(5, df_train, 'watched'))]))

with open('ans_2', 'w') as fout:
    fout.write(' '.join([str(average_recall(1, df_test, 'watched')),
                         str(average_precision(1, df_test, 'watched')),
                         str(average_recall(5, df_test, 'watched')),
                         str(average_precision(5, df_test, 'watched'))]))

with open('ans_3', 'w') as fout:
    fout.write(' '.join([str(average_recall(1, df_train, 'bought')),
                         str(average_precision(1, df_train, 'bought')),
                         str(average_recall(5, df_train, 'bought')),
                         str(average_precision(5, df_train, 'bought'))]))

with open('ans_4', 'w') as fout:
    fout.write(' '.join([str(average_recall(1, df_test, 'bought')),
                         str(average_precision(1, df_test, 'bought')),
                         str(average_recall(5, df_test, 'bought')),
                         str(average_precision(5, df_test, 'bought'))]))

In [164]:
df_train.head()

                                              watched        bought
7   [59, 60, 61, 62, 60, 63, 64, 65, 66, 61, 67, 6...  [67, 60, 63]
10   [84, 85, 86, 87, 88, 89, 84, 90, 91, 92, 93, 86]          [86]
19                               [138, 198, 199, 127]         [199]
30  [303, 304, 305, 306, 307, 308, 309, 310, 311, ...         [303]
33                                    [352, 353, 352]         [352]

In [165]:
df_test.head()

                                     watched   bought
7   [63, 68, 69, 70, 66, 61, 59, 61, 66, 68]    66,63
14            [158, 159, 160, 159, 161, 162]      162
19                 [200, 201, 202, 203, 204]  201,205
34                           [371, 372, 371]  371,373
40                                     [422]      422

In [167]:
df_test['bought'] = df_test['bought'].apply(lambda x: x.split(','))